# Generated by Django 5.2.6 on 2025-09-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sugar_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
