# Generated by Django 5.2.6 on 2025-10-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_patient_blood_pressure_patient_heart_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='risk_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
